### ISSUE TITLE
"RelyingParty default authentication parameters are missing" when multiuser=false

### ISSUE THREAD

**Issue by gobengo** [interop-alliance/life-server#32]
Reproduction Steps:

1. Check out efb93516393e407e30f97687e6731588d732ed00 (master right now)
2. Generate a self-signed ssl cert with:
    ```
    openssl req     -new     -newkey rsa:4096     -days 365     -nodes     -x509     -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com"     -keyout privkey.pem     -out fullchain.pem
    ```
3. Write config.json as
    ```
    {
      "root": "./data/root",
      "port": "8443",
      "serverUri": "https://localhost:8443",
      "webid": true,
      "mount": "/",
      "configPath": "./config",
      "dbPath": "./data/db",
      "sslKey": "./privkey.pem",
      "sslCert": "./fullchain.pem",
      "multiuser": false,
      "server": {
        "name": "",
        "description": "",
        "logo": ""
      },
      "supportEmail": "Your support email address"
    }
    ```
3. Run `NODE_TLS_REJECT_UNAUTHORIZED=0 ./bin/solid-test start`
4. Open https://localhost:8443 in your web browser, probably choosing to ignore the insecure self-signed cert
5. Click 'submit' on the "Select Provider" form

Expected Behavior:
* I'm not sure, I haven't had it work.
* No errors

Actual Behavior
* I see the same form, but with an error above it: "RelyingParty default authentication parameters are missing"

Notes
* This doesn't happen when multiuser=true

**Comment by gobengo** [comment]
@dmitrizagidulin I could still reproduce this on e84f102392b39b9946bb1e6163f5e84f95bd592d.

But then I removed my dbPath and root directories, and then it worked.

**Comment by dmitrizagidulin** [comment]
Ok, so I think this was just due to an old config (since removing the db and root paths fixed it). 
Closing for the moment, but let me know if you encounter it again.
