### ISSUE TITLE
Error launching Life-Server in Windows development environment 

### ISSUE THREAD

**Issue by KarlHRichter** [interop-alliance/life-server#52]
Using Windows 10 with Visual Studio and Linux Bash Shell. It is possible to install and initialise the server, but not to run the server, which fails on start. See logs below.
```
$ npm start

life-server@7.0.0 start D:\GitHubRepos\life-server2
./bin/server-test start

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! life-server@7.0.0 start: `./bin/server-test start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the life-server@7.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\[anonymised]-debug.log
```

**Comment by dmitrizagidulin** [comment]
Hi @KarlHRichter, thanks for the heads up! I think I know the source of the problem; will test the fix on Windows and get back to you.

**Comment by dmitrizagidulin** [comment]
@KarlHRichter - I've finally got WSL 2 working on my Windows box, so, am testing this now :)

**Comment by dmitrizagidulin** [comment]
@KarlHRichter I think I have a fix for this in PR #54. (I made sure to test on my Windows 10 powershell and bash shell both).

So, try this:

1. `git pull` a fresh copy of `main` branch
2. Do an `npm install` (the fix added another package)
3. Now try launching with `npm start` (no init necessary by default)

**Comment by KarlHRichter** [comment]
Many thanks @dmitrizagidulin - yes, that's resolved the issue. I managed to get it running in my Windows dev environment. Much appreciated!

**Comment by dmitrizagidulin** [comment]
@KarlHRichter - excellent! I'm closing this issue, then.
